### ISSUE TITLE
v3.6.0 update site only offers v3.5.0

### ISSUE THREAD

**Issue by fireandfuel** [eclipse-efx/efxclipse-eclipse#76]
The [3.6.0 update site](https://download.eclipse.org/efxclipse/updates-released/3.6.0/site/) only offers the 3.5.0 release which is incompatible with eclipse 2020-06 (4.16.0).

It results in that efxclipse can't be installed from the Eclipse marketplace for 2020-06, even it says that it's compatible.

**Comment by martinbluehweis** [comment]
unfortunately the version number is not correct in 3.6.0, but the repository content is.

we already updated the platform for the runtime, looks like we also need to update it for the tooling. I opened #77 for that.

**Comment by tomsontom** [comment]
Has anyone tried to use the nightly-site?

**Comment by martinbluehweis** [comment]
> Has anyone tried to use the nightly-site?

works for me (2020-06)

**Comment by fireandfuel** [comment]
> Has anyone tried to use the nightly-site?

Yes, it  works with eclipse 2020-06. I've installed version 3.7.0.202006220700.

**Comment by nuravgrag** [comment]
Hmm so i tried installing it on Eclipse 2020-06 and I followed your blog Tom: https://tomsondev.bestsolution.at/2020/01/28/setting-up-efxclipse-rcp-development-for-java11-and-pde/. When i try to install the Target Platform Feature I am thrown the following dependency problem:

`Cannot complete the install because of a conflicting dependency.
  Software being installed: e(fx)clipse - Target Platform Feature 3.7.0.202008250600 (org.eclipse.fx.target.feature.feature.group 3.7.0.202008250600)
  Software currently installed: Eclipse Platform 4.16.0.v20200604-0951 (org.eclipse.platform.feature.group 4.16.0.v20200604-0951)
  Only one of the following can be installed at once: 
    Equinox Java Authentication and Authorization Service (JAAS) 1.3.400.v20191008-0645 (org.eclipse.equinox.security 1.3.400.v20191008-0645)
    Equinox Java Authentication and Authorization Service (JAAS) 1.3.500.v20200114-1637 (org.eclipse.equinox.security 1.3.500.v20200114-1637)
    Equinox Java Authentication and Authorization Service (JAAS) 1.2.300.v20170505-1235 (org.eclipse.equinox.security 1.2.300.v20170505-1235)
  Cannot satisfy dependency:
    From: e(fx)clipse - Target Platform Feature 3.7.0.202008250600 (org.eclipse.fx.target.feature.feature.group 3.7.0.202008250600)
    To: org.eclipse.equinox.p2.iu; org.eclipse.equinox.security [1.3.400.v20191008-0645,1.3.400.v20191008-0645]
  Cannot satisfy dependency:
    From: Eclipse Platform 4.16.0.v20200604-0951 (org.eclipse.platform.feature.group 4.16.0.v20200604-0951)
    To: org.eclipse.equinox.p2.iu; org.eclipse.equinox.security [1.3.500.v20200114-1637,1.3.500.v20200114-1637]`

Any idea how I can resolve this? I am using the nightly-site.
