### ISSUE TITLE
Update to current Eclipse platform

### ISSUE THREAD

**Issue by martinbluehweis** [eclipse-efx/efxclipse-eclipse#77]
#76 says the tooling ist not installable in 2020-6.

**Comment by fireandfuel** [comment]
Is there any progress on this?

**Comment by tomsontom** [comment]
I successfully installed the nightly into my Eclipse-2020-09 release candidate

**Comment by fireandfuel** [comment]
Is there a plan to release nightly as v3.7.0 to the update site and **officially** support Eclipse 2020-06 and 2020-09? 
I guess some users install it from the Eclipse marketplace and get a very old 3.5.0 build which is broken for 2020-06 and newer.

Seriously guys, why does @tomsontom simply set the *supported* version to Eclipse 2020-06 and 2020-09 at the [Eclipse Marketplace](https://marketplace.eclipse.org/content/efxclipse) and not release the artifacts for it to the update site?

What's the cause of this issue?

**Comment by tomsontom** [comment]
so i how can he dare to declare it compatible this sucker ;-) - probably he's too dumb?!? - well maybe because it is compatible and can be installed - I just used:
* https://download.eclipse.org/eclipse/downloads/drops4/R-4.16-202006040540/
* added http://download.eclipse.org/efxclipse/updates-released/3.6.0/site
* (yes the install wizard gave me a warning that it needs to modify the installed items because of guava-21 or something like that)

and then I got:
<img width="1231" alt="Bildschirmfoto 2020-09-21 um 20 13 39" src="https://user-images.githubusercontent.com/52631/93804785-14333800-fc47-11ea-8497-7d1253e62c4d.png">
and to proof that I'm not cheating:
<img width="963" alt="Bildschirmfoto 2020-09-21 um 20 14 17" src="https://user-images.githubusercontent.com/52631/93804872-2f05ac80-fc47-11ea-88c7-932ca23846b5.png">

The cause of us not releasing that often is that we are not payed to do that (well in fact I'm not payed, Martin is by my company but he also does stuff sometimes in his spare time) and we are doing this all for free. 

I agree we could to better, I agree that it is no perfect the way things are but the IDE support is not what we are payed for and it looks like all our customers who depend on the runtime-platform have not been running into problems and as I just proofed above it is definately installable in 2020-06.

So while I'm not saying you are wrong. It might be that the current release can not be installed via market-place this sounds more like an issue of the markplace-client than an e(fx)clipse problem. I understand that for you as an enduser that does not matter.

PS: IIRC plug-ins in the marketplace are declared compatible by default with the latest version (my educated guess is that marketplace believes platform does use semantic versioning - which it apparently does not - and marks a plug-ins compatible based upon that fact).

PS-2: If you look at https://projects.eclipse.org/projects/technology.efxclipse you noticed we have set a release date for 3.7.0 to be the 10.10.2020 cool eh.

PS-3: You are not happy - join the fun and contribute
